name: message
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.1"

dependencies:
  flutter:
    sdk: flutter

  badges: ^2.0.2
  page_transition: ^2.0.5
  animations: ^2.0.2
  firebase_core: ^1.16.0
  firebase_messaging: ^11.3.0
  firebase_database: ^9.0.14
  firebase_storage: ^10.3.1
  cloud_firestore: ^3.1.14
  flutter_local_notifications: ^9.5.2
  shared_preferences: ^2.0.15
  http: ^0.13.4
  firebase_auth: ^3.3.18
  crypto: ^3.0.2
  provider: ^6.0.2
  flutter_contacts: ^1.1.5
  image_picker: ^0.8.5+3
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
